backend/flask/blueprints/search_bar/routes.py
from flask import Blueprint, render_template, abort
from jinja2.exceptions import TemplateNotFound
from sqlalchemy.orm import Session
from database.database import engine
import interfaces.album as album
import interfaces.artist as artist
import interfaces.track as track
from flask import request

search_page = Blueprint('search_page', __name__,
                        template_folder='./templates/search_bar')
                        
@search_page.get('/search')
def search():
    try:
        word = request.args.getlist('q')[0]
        with Session(engine) as session:
            albums= album.get_match(word, session)
            tracks = track.get_match(word, session)
            artists = artist.get_match(word, session)
            
        context = {
            'title': 'Search Results',
            'tracks': [track.dict() for track in tracks],
            'albums': albums,
            'artists': artists
        }

        return render_template('search.html', **context)
    except TemplateNotFound:
        print('error')
        abort(404)

backend/flask/templates/jinja2/base.html
<!-- Jinja2 is used for all html templates -->
<!DOCTYPE html>
<html lang="en">

<head>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge"> {% block title %}
    <title>Homepage</title>{% endblock %}
    <!-- what shows up on search engine -->
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="/static/css/style.css">
</head>

<body>
    <header>
        <h1>Spotify (almost)</h1>
    </header>
    <div class="page-layout">

        <nav>
            <h2>Menu</h2>
            <ul>
                <!-- for loop -->
                {% for el in ['homepage', 'albums', 'artists', 'tracks']%}
                <li><a href="{{url_for(el + '_page' + '.' + el)}}"> {{el | capitalize}}</a></li>
                {% endfor %}
            </ul>
            <form action="{{url_for('search_page.search')}}">
                <input type="search" name="q" placeholder="Search ...">
                <input type="submit" value="Go!">
            </form>
        </nav>
        <main>
            <!-- block content -->
            {% block content %} content goes here {% endblock %}
        </main>
    </div>
    <footer class="music-player">
        <div>
            <button class='prev-btn' onclick="playPrevious()">Previous</button>
            <button class='play-btn' onclick="playPause()">Play</button>
            <button class='next-btn' onclick="playNext()">Next</button>
        </div>
        <div class="player-img">
            <img class='player-cover' src="/static/images/music-placeholder.png" alt="album cover">
        </div>
        <div>
            <span class="player-song-name"> No song is playing</span>
            <br>
            <span class="player-album"></span>
            <br>
            <span class="player-artist"></span>
            <br>
            <input class="player-slider" type="range" min="1" max="100" value="0" onchange="setSlider()">
        </div>
        <div class="volume">
            <span>Volume</span>
            <input class="player-volume" type="range" min="1" max="100" value="30" onchange="setVolume()">
        </div>
    </footer>
    <script src="/static/js/player.js"></script>
</body>



</html>