backend/flask/blueprints/albums/routes.py
from flask import Blueprint, render_template, abort, url_for
from jinja2.exceptions import TemplateNotFound
import interfaces.album as album
from sqlalchemy.orm import Session
from database.database import engine
import json

album_page = Blueprint('albums_page', __name__,
                       template_folder='templates/albums')
                       
@album_page.get('/albums')
def albums():
    try:
        with Session(engine) as session:
            albums = album.get_all(session)
        context = {
            'title': 'Albums',
            'albums': albums
        }
        return render_template('albums.html', **context)
    except TemplateNotFound:
        print('error')
        abort(404)
        
        
@album_page.get('/albums/<int:id>')   
def goto_id(id: int):
    """
    It gets the tracks for the album with the given id, and then renders the template with the tracks
    and album information
    
    :param id: the id of the album
    :type id: int
    :return: A list of dictionaries
    """
    try:
        with Session(engine) as session:
            tracks = album.get_tracks(id, session)
        album_name = tracks[0].album.name
        album_cover = tracks[0].album.img_cover
        
        context = {
            'title': album_name,
            'album_name': album_name,
            'album_cover':album_cover,
            'tracks': [track.dict() for track in tracks]
        }
        return render_template('albums_tracks.html', **context)
    except TemplateNotFound:
        print('error')
        abort(404)

backend/flask/blueprints/artists/routes.py
from flask import Blueprint, render_template, abort
from jinja2.exceptions import TemplateNotFound
from sqlalchemy.orm import Session
from database.database import engine
import interfaces.artist as artist


artist_page = Blueprint('artists_page', __name__,
                        template_folder='./templates/artists')
                        
                        
@artist_page.get('/artist')
def artists():
    try:
        with Session(engine) as session:
            artists = artist.get_all(session)
        context = {
            'title': 'Artists',
            'artists': artists
        }
        return render_template('artists.html', **context)
    except TemplateNotFound:
        print('error')
        abort(404)

@artist_page.get('/artists/<int:id>/info')   
def goto_artist(id: int):
    try:
        with Session(engine) as session:
            art = artist.get_artist(id, session)[0]
        context = {
            'title': art.name,
            'artist_img': art.artist_img,
            'tracks': [track.dict() for track in art.tracks],
            'albums': art.albums
        }
        return render_template('artists_info.html', **context)
    except TemplateNotFound:
        print('error')
        abort(404)

backend/flask/templates/jinja2/macros/macros.html
{% macro display(l=[], class1="", class2="", class3="", name="", propriety="", route="") -%}
<section class="{{class1 + ' ' + class3}}"">
    <h2>{{name}}</h2>
    <div class={{class2}}>
        <div>{% for el in l %}
            <a href=" {{url_for(route, id=el.id)}}"><img src={{el[propriety]}} alt="cover"></a>
    {% endfor %}
    </div>

    </div>
</section>
{%- endmacro %} {% macro display_tracks(l=[], name="") -%}
<h2>{{name}}</h2>
<div class="tracks" onmouseover="set_track_list({{l}})">
    {% for el in l%}
    <div class="track">
        <span><u>Track Name:</u><br><br><a onclick='loadTrack({{el}})'>{{el['name']}}</a></span>
        <span><u>Album Name:</u> <br><br><a
                href="{{url_for('albums_page.goto_id', id=el.album_id)}}">{{el['album']['name']}}</a></span>
        <span><u>Artist:</u><br><br>
            {% for artist in el.artists %}
            <a href="{{url_for('artists_page.goto_artist', id=artist.id)}}">{{artist.name}}</a><br>
            {% endfor %}
        </span>
        <span><u>Duration:</u><br><br>{{el['duration']}}</span>
    </div>
    {% endfor %}
</div>


{%- endmacro %}